// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.3
// source: job_request.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageType int32

const (
	ImageType_CONTENT ImageType = 0
	ImageType_STYLE   ImageType = 1
)

// Enum value maps for ImageType.
var (
	ImageType_name = map[int32]string{
		0: "CONTENT",
		1: "STYLE",
	}
	ImageType_value = map[string]int32{
		"CONTENT": 0,
		"STYLE":   1,
	}
)

func (x ImageType) Enum() *ImageType {
	p := new(ImageType)
	*p = x
	return p
}

func (x ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_job_request_proto_enumTypes[0].Descriptor()
}

func (ImageType) Type() protoreflect.EnumType {
	return &file_job_request_proto_enumTypes[0]
}

func (x ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageType.Descriptor instead.
func (ImageType) EnumDescriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{0}
}

type GiveJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
}

func (x *GiveJobRequest) Reset() {
	*x = GiveJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveJobRequest) ProtoMessage() {}

func (x *GiveJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveJobRequest.ProtoReflect.Descriptor instead.
func (*GiveJobRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{0}
}

func (x *GiveJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GiveJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageChunk []byte    `protobuf:"bytes,1,opt,name=imageChunk,proto3" json:"imageChunk,omitempty"`
	ImageType  ImageType `protobuf:"varint,2,opt,name=imageType,proto3,enum=web_nst.ImageType" json:"imageType,omitempty"`
	RequestId  string    `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	WorkerId   string    `protobuf:"bytes,4,opt,name=workerId,proto3" json:"workerId,omitempty"`
	JobGiven   bool      `protobuf:"varint,5,opt,name=jobGiven,proto3" json:"jobGiven,omitempty"`
}

func (x *GiveJobResponse) Reset() {
	*x = GiveJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveJobResponse) ProtoMessage() {}

func (x *GiveJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveJobResponse.ProtoReflect.Descriptor instead.
func (*GiveJobResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{1}
}

func (x *GiveJobResponse) GetImageChunk() []byte {
	if x != nil {
		return x.ImageChunk
	}
	return nil
}

func (x *GiveJobResponse) GetImageType() ImageType {
	if x != nil {
		return x.ImageType
	}
	return ImageType_CONTENT
}

func (x *GiveJobResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GiveJobResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GiveJobResponse) GetJobGiven() bool {
	if x != nil {
		return x.JobGiven
	}
	return false
}

type JobProgressData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId        string  `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	RequestId       string  `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ProgressPercent float32 `protobuf:"fixed32,3,opt,name=progressPercent,proto3" json:"progressPercent,omitempty"`
}

func (x *JobProgressData) Reset() {
	*x = JobProgressData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobProgressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgressData) ProtoMessage() {}

func (x *JobProgressData) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgressData.ProtoReflect.Descriptor instead.
func (*JobProgressData) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{2}
}

func (x *JobProgressData) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobProgressData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *JobProgressData) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

type Ok struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ok) Reset() {
	*x = Ok{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{3}
}

type JobEndRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageChunk []byte `protobuf:"bytes,1,opt,name=imageChunk,proto3" json:"imageChunk,omitempty"`
	RequestId  string `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	WorkerId   string `protobuf:"bytes,3,opt,name=workerId,proto3" json:"workerId,omitempty"`
}

func (x *JobEndRequest) Reset() {
	*x = JobEndRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEndRequest) ProtoMessage() {}

func (x *JobEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEndRequest.ProtoReflect.Descriptor instead.
func (*JobEndRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{4}
}

func (x *JobEndRequest) GetImageChunk() []byte {
	if x != nil {
		return x.ImageChunk
	}
	return nil
}

func (x *JobEndRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *JobEndRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_job_request_proto protoreflect.FileDescriptor

var file_job_request_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6a, 0x6f, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x77, 0x65, 0x62, 0x5f, 0x6e, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x0e,
	0x47, 0x69, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb9, 0x01, 0x0a, 0x0f, 0x47,
	0x69, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x30,
	0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x77, 0x65, 0x62, 0x5f, 0x6e, 0x73, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6a, 0x6f,
	0x62, 0x47, 0x69, 0x76, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6a, 0x6f,
	0x62, 0x47, 0x69, 0x76, 0x65, 0x6e, 0x22, 0x75, 0x0a, 0x0f, 0x4a, 0x6f, 0x62, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22, 0x04, 0x0a,
	0x02, 0x4f, 0x6b, 0x22, 0x69, 0x0a, 0x0d, 0x4a, 0x6f, 0x62, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x2a, 0x23,
	0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43,
	0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x59, 0x4c,
	0x45, 0x10, 0x01, 0x32, 0xb5, 0x01, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x47, 0x69, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x17, 0x2e,
	0x77, 0x65, 0x62, 0x5f, 0x6e, 0x73, 0x74, 0x2e, 0x47, 0x69, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x77, 0x65, 0x62, 0x5f, 0x6e, 0x73, 0x74,
	0x2e, 0x47, 0x69, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x12, 0x36, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x2e, 0x77, 0x65, 0x62, 0x5f, 0x6e, 0x73, 0x74, 0x2e, 0x4a, 0x6f, 0x62, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0b, 0x2e, 0x77, 0x65,
	0x62, 0x5f, 0x6e, 0x73, 0x74, 0x2e, 0x4f, 0x6b, 0x28, 0x01, 0x12, 0x2f, 0x0a, 0x06, 0x4a, 0x6f,
	0x62, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x2e, 0x77, 0x65, 0x62, 0x5f, 0x6e, 0x73, 0x74, 0x2e, 0x4a,
	0x6f, 0x62, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x77,
	0x65, 0x62, 0x5f, 0x6e, 0x73, 0x74, 0x2e, 0x4f, 0x6b, 0x28, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x6e,
	0x73, 0x74, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_job_request_proto_rawDescOnce sync.Once
	file_job_request_proto_rawDescData = file_job_request_proto_rawDesc
)

func file_job_request_proto_rawDescGZIP() []byte {
	file_job_request_proto_rawDescOnce.Do(func() {
		file_job_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_job_request_proto_rawDescData)
	})
	return file_job_request_proto_rawDescData
}

var file_job_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_job_request_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_job_request_proto_goTypes = []interface{}{
	(ImageType)(0),          // 0: web_nst.ImageType
	(*GiveJobRequest)(nil),  // 1: web_nst.GiveJobRequest
	(*GiveJobResponse)(nil), // 2: web_nst.GiveJobResponse
	(*JobProgressData)(nil), // 3: web_nst.JobProgressData
	(*Ok)(nil),              // 4: web_nst.Ok
	(*JobEndRequest)(nil),   // 5: web_nst.JobEndRequest
}
var file_job_request_proto_depIdxs = []int32{
	0, // 0: web_nst.GiveJobResponse.imageType:type_name -> web_nst.ImageType
	1, // 1: web_nst.JobService.GiveJob:input_type -> web_nst.GiveJobRequest
	3, // 2: web_nst.JobService.JobProgress:input_type -> web_nst.JobProgressData
	5, // 3: web_nst.JobService.JobEnd:input_type -> web_nst.JobEndRequest
	2, // 4: web_nst.JobService.GiveJob:output_type -> web_nst.GiveJobResponse
	4, // 5: web_nst.JobService.JobProgress:output_type -> web_nst.Ok
	4, // 6: web_nst.JobService.JobEnd:output_type -> web_nst.Ok
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_request_proto_init() }
func file_job_request_proto_init() {
	if File_job_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_job_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobProgressData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ok); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobEndRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_request_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_request_proto_goTypes,
		DependencyIndexes: file_job_request_proto_depIdxs,
		EnumInfos:         file_job_request_proto_enumTypes,
		MessageInfos:      file_job_request_proto_msgTypes,
	}.Build()
	File_job_request_proto = out.File
	file_job_request_proto_rawDesc = nil
	file_job_request_proto_goTypes = nil
	file_job_request_proto_depIdxs = nil
}
