version: '3'
services:
  redis:
    image: 'bitnami/redis:7.0.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    expose:
      - "6379"
    ports:
      - "6379:6379"
