version: '3'
services:
  redis:
    image: 'bitnami/redis:7.0.0'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
  backend:
    restart: always
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "8150:8080"
      - "0.0.0.0:50051:50051"
